#!/bin/bash

CONFIG="$HOME/.config/alacritty/alacritty.yml"

if [ "$1" == "--float" ]; then
	alacritty -o font.size=18 --class 'alacritty-float,alacritty-float' --config-file "$CONFIG" -e tmux attach
elif [ "$1" == "--float-new" ]; then
	alacritty -o font.size=18 --class 'alacritty-float,alacritty-float' --config-file "$CONFIG" -e tmux
elif [ "$1" == "--new" ]; then
	alacritty -o font.size=18 --config-file "$CONFIG" -e tmux
else
	alacritty -o font.size=18 --config-file "$CONFIG" -e tmux attach
fi

