[module/wired]
type = internal/network
;interface = enp1s0f2
interface-type = wired
interval = 1.0

format-connected = <label-connected>
format-connected-prefix = %{T13}
format-connected-prefix-background = ${colors.green}
format-connected-prefix-foreground = ${colors.black}
format-connected-prefix-padding = 1.8
format-connected-underline = ${colors.green}
label-connected = %{T2}%downspeed%%{T-}
label-connected-background = ${colors.bg-alt}
label-connected-foreground = ${colors.fg}
label-connected-padding = 1.8

format-disconnected = <label-disconnected>
format-disconnected-prefix = %{T13}
format-disconnected-prefix-background = ${colors.red}
format-disconnected-prefix-foreground = ${colors.black}
format-disconnected-prefix-padding = 1
format-disconnected-underline = ${colors.red}
label-disconnected = %{T10}%{T-}
label-disconnected-background = ${colors.bg-alt}
label-disconnected-foreground = ${colors.red}
label-disconnected-padding = 1
