theme = "github_dark_high_contrast"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[keys.insert]
C-c = ["normal_mode", "collapse_selection"]
j = { k = "normal_mode"}
k = { j = "normal_mode"}

[keys.normal]
C-d = ["half_page_down", "align_view_middle", "goto_window_center"]
C-u = ["half_page_up", "align_view_middle", "goto_window_center"]
C-f = ":sh tmux split-window -h Hx"
C-h = ":sh tmux new-window Hx"
C-s = ":w"
C-j = "copy_selection_on_next_line"
C-k = "copy_selection_on_prev_line"
C-c = ["normal_mode", "collapse_selection"]
"ret" = ["open_below", "normal_mode"]
X = "extend_line_above"

[keys.select]
C-d = ["half_page_down", "align_view_middle", "goto_window_center"]
C-u = ["half_page_up", "align_view_middle", "goto_window_center"]
C-f = ":sh tmux split-window -h Hx"
C-h = ":sh tmux new-window Hx"
C-s = ":w"
C-j = "copy_selection_on_next_line"
C-k = "copy_selection_on_prev_line"
C-c = ["normal_mode", "collapse_selection"]
X = "extend_line_above"

[keys.normal.space]
"space" = "file_picker"
a = "buffer_picker"
q = ":quit"
r = "replace_selections_with_clipboard"

[keys.select.space]
"space" = "file_picker"
a = "buffer_picker"
q = ":quit"

[keys.normal.space.c]
a = "code_action"
c = "toggle_comments"
d = ":reset-diff-change"


[keys.select.space.c]
a = "code_action"
c = "toggle_comments"
d = ":reset-diff-change"
