#!/bin/sh
xrandr --output HDMI-A-1 --primary --mode 1920x1080 --rate 75 --pos 1920x0 --rotate normal --output DVI-D-0 --off --output DisplayPort-1-0 --off --output DisplayPort-1-1 --off --output DisplayPort-1-2 --off --output HDMI-A-1-0 --mode 1920x1080 --pos 0x0 --rotate normal
