#!/usr/bin/env bash

CONFIG="$HOME/dotfiles/alacritty/alacritty.toml"

if [ "$1" == "--float" ]; then
	alacritty  --class 'alacritty-float,alacritty-float' --config-file "$CONFIG" -e tmux attach
elif [ "$1" == "--float-new" ]; then
	alacritty  --class 'alacritty-float,alacritty-float' --config-file "$CONFIG" -e tmux
elif [ "$1" == "--new" ]; then
	alacritty  --config-file "$CONFIG" -e tmux
else
	alacritty  --config-file "$CONFIG" -e tmux attach
fi
