import = ["/home/kenobi/.config/i3/alacritty/colors.toml", "/home/kenobi/.config/i3/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[shell]
program = "/bin/fish"

[window]
decorations = "full"
dynamic_title = true
# history = 10000
# multiplier = 3
opacity = 1
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 5
y = 5
